<#
.SYNOPSIS
    One-time IIS setup for the FIT API / MAKE ME FIT site (mmfit.space).

.DESCRIPTION
    Creates everything Deploy-Site.ps1 expects to already exist:
      - the App Pool (No Managed Code - correct for ASP.NET Core, which does not
        load the .NET Framework CLR)
      - the IIS site and its host-header bindings
      - the server-owned directories that deploys must never delete
      - write permissions for the App Pool identity on those directories
      - the two SYSTEM scheduled tasks that let a NON-ADMIN deploy runner start
        and stop the App Pool, and nothing else

    Safe to re-run: every step is idempotent.

    This server also hosts Healixa.Web, whose port 80 binding has a BLANK host
    header (http://*:80:) and so acts as a catch-all. IIS prefers an exact
    host-header match, so the bindings added here win for mmfit.space and
    www.mmfit.space while Healixa keeps serving everything else. Nothing about
    Healixa is modified.

.EXAMPLE
    .\iis-setup.ps1
#>
[CmdletBinding()]
param(
    [string]$SiteName     = 'MMFit.Web',
    [string]$AppPoolName  = 'MMFitWeb',
    [string]$PhysicalPath = 'C:\MMFit\sites\Web',
    [string[]]$HostNames  = @('mmfit.space', 'www.mmfit.space'),
    [string]$RunnerAccount = 'MMFitRunner'
)

$ErrorActionPreference = 'Stop'
Import-Module WebAdministration

Write-Host "=== IIS setup: $SiteName ===" -ForegroundColor Cyan

# ------------------------------------------------------------------ directories
# These live only on the server and are excluded from robocopy /MIR by
# Deploy-Site.ps1. Creating them here means a deploy never has to.
$dirs = @{
    $PhysicalPath                                        = 'site root'
    (Join-Path $PhysicalPath 'uploads\avatars')          = 'user-uploaded avatars (Storage:AvatarRoot)'
    (Join-Path $PhysicalPath 'logs')                     = 'ASP.NET Core Module stdout logs'
    (Join-Path $PhysicalPath '.well-known\acme-challenge') = "Let's Encrypt HTTP-01 challenge root"
}
foreach ($d in $dirs.Keys) {
    if (-not (Test-Path $d)) {
        New-Item -ItemType Directory -Path $d -Force | Out-Null
        Write-Host "  created $d  <- $($dirs[$d])" -ForegroundColor Green
    }
}

# ACME challenge tokens are EXTENSIONLESS files. IIS's static file handler refuses
# to serve a file whose extension has no MIME mapping, so without this web.config
# the token returns 404.3 and BOTH first issuance and every later renewal fail.
$acmeWebConfig = Join-Path $PhysicalPath '.well-known\acme-challenge\web.config'
if (-not (Test-Path $acmeWebConfig)) {
    @'
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <staticContent>
      <clear />
      <mimeMap fileExtension=".*" mimeType="text/plain" />
    </staticContent>
    <handlers>
      <clear />
      <add name="StaticFile" path="*" verb="*" type="" modules="StaticFileModule"
           scriptProcessor="" resourceType="Either" requireAccess="Read" />
    </handlers>
  </system.webServer>
</configuration>
'@ | Set-Content -Path $acmeWebConfig -Encoding UTF8
    Write-Host '  created acme-challenge web.config (extensionless MIME mapping)' -ForegroundColor Green
}

# ------------------------------------------------------------------ app pool
if (-not (Test-Path "IIS:\AppPools\$AppPoolName")) {
    New-WebAppPool -Name $AppPoolName | Out-Null
    Write-Host "  created app pool $AppPoolName" -ForegroundColor Green
}
# Empty managedRuntimeVersion == "No Managed Code". ASP.NET Core runs out of
# process from the CLR that this setting controls, so loading it would be waste.
Set-ItemProperty "IIS:\AppPools\$AppPoolName" -Name managedRuntimeVersion -Value ''
Set-ItemProperty "IIS:\AppPools\$AppPoolName" -Name startMode -Value 'AlwaysRunning'
# The app applies EF migrations on boot and builds its Identity model on first
# request. Letting IIS idle-shutdown the worker would make some visitor pay that
# cost at random.
Set-ItemProperty "IIS:\AppPools\$AppPoolName" -Name processModel.idleTimeout -Value '00:00:00'
Set-ItemProperty "IIS:\AppPools\$AppPoolName" -Name recycling.periodicRestart.time -Value '00:00:00'
Write-Host '  app pool configured (No Managed Code, AlwaysRunning, no idle timeout)' -ForegroundColor Gray

# ASPNETCORE_ENVIRONMENT must be Production or appsettings.Production.json - which
# holds the connection string and the Google secret - is never loaded, and the app
# silently falls back to appsettings.json's Docker-oriented defaults
# (Host=db, Smtp=mail) and fails to reach the database.
#
# Set on the APP POOL rather than in web.config on purpose: web.config is
# regenerated by `dotnet publish` and overwritten by every deploy, so a value put
# there would have to be re-applied forever. The app pool setting survives deploys.
$envVars = Get-ItemProperty "IIS:\AppPools\$AppPoolName" -Name environmentVariables
if (-not ($envVars.Collection | Where-Object { $_.name -eq 'ASPNETCORE_ENVIRONMENT' })) {
    Add-WebConfigurationProperty -PSPath 'MACHINE/WEBROOT/APPHOST' `
        -Filter "system.applicationHost/applicationPools/add[@name='$AppPoolName']/environmentVariables" `
        -Name '.' -Value @{ name = 'ASPNETCORE_ENVIRONMENT'; value = 'Production' }
    Write-Host '  ASPNETCORE_ENVIRONMENT=Production set on the app pool' -ForegroundColor Green
} else {
    Write-Host '  = ASPNETCORE_ENVIRONMENT already set on the app pool' -ForegroundColor Gray
}

# ------------------------------------------------------------------ site
if (-not (Test-Path "IIS:\Sites\$SiteName")) {
    New-Website -Name $SiteName -PhysicalPath $PhysicalPath -ApplicationPool $AppPoolName `
                -Port 80 -HostHeader $HostNames[0] | Out-Null
    Write-Host "  created site $SiteName -> $PhysicalPath" -ForegroundColor Green
} else {
    Set-ItemProperty "IIS:\Sites\$SiteName" -Name physicalPath    -Value $PhysicalPath
    Set-ItemProperty "IIS:\Sites\$SiteName" -Name applicationPool -Value $AppPoolName
    Write-Host "  site $SiteName already exists - settings reasserted" -ForegroundColor Yellow
}

foreach ($h in $HostNames) {
    $existing = Get-WebBinding -Name $SiteName -Protocol http -ErrorAction SilentlyContinue |
                Where-Object { $_.bindingInformation -eq "*:80:$h" }
    if (-not $existing) {
        New-WebBinding -Name $SiteName -Protocol http -Port 80 -HostHeader $h
        Write-Host "  + http binding  *:80:$h" -ForegroundColor Green
    }
}

# ------------------------------------------------------------------ permissions
function Grant-Path {
    param([string]$Path, [string]$Identity, [string]$Rights)
    $acl  = Get-Acl $Path
    $rule = New-Object Security.AccessControl.FileSystemAccessRule(
        $Identity, $Rights, 'ContainerInherit,ObjectInherit', 'None', 'Allow')
    $acl.AddAccessRule($rule)
    Set-Acl -Path $Path -AclObject $acl
    Write-Host "  $Rights for $Identity on $Path" -ForegroundColor Gray
}

# The worker process writes avatars and stdout logs at runtime.
$poolIdentity = "IIS AppPool\$AppPoolName"
Grant-Path -Path (Join-Path $PhysicalPath 'uploads') -Identity $poolIdentity -Rights 'Modify'
Grant-Path -Path (Join-Path $PhysicalPath 'logs')    -Identity $poolIdentity -Rights 'Modify'
# Read is enough for the rest of the site - the app never writes to its own binaries.
Grant-Path -Path $PhysicalPath -Identity $poolIdentity -Rights 'ReadAndExecute'

# ------------------------------------------------------------------ pool control tasks
# The deploy runner is NOT an administrator, so it cannot start or stop an App
# Pool directly. These two scheduled tasks run as SYSTEM and do exactly one fixed
# thing each. The runner may trigger them and nothing else - it cannot edit them,
# because it is not an admin. That is the whole point: least privilege that still
# allows a deploy.
$appcmd = "$env:SystemRoot\System32\inetsrv\appcmd.exe"
$tasks = @{
    "MMFit-StopPool-Web"  = "stop apppool /apppool.name:$AppPoolName"
    "MMFit-StartPool-Web" = "start apppool /apppool.name:$AppPoolName"
}

# The security descriptor MUST be supplied when the task is REGISTERED. A task's
# default SD grants rights only to Administrators and SYSTEM, and it cannot be
# widened afterwards: the descriptor lives under
# HKLM\...\Schedule\TaskCache\Tree\<task>, which is owned by SYSTEM and denies
# writes even to Administrators ("Requested registry access is not allowed").
#
# Verified on this box 2026-07-29: with the default SD, `schtasks /run` as
# MMFitRunner returns "ERROR: Access is denied." and the pool never changes state
# - so the deploy would hang until it timed out.
#
# Register-ScheduledTask has no SDDL parameter, so the COM scheduler API is used
# instead: RegisterTaskDefinition takes the SDDL as its final argument.
#
#   FA       full control           -> Administrators, SYSTEM
#   0x1200a9 read + execute         -> the runner: enough to RUN the task,
#                                      not enough to change what it does
$runner = Get-LocalUser -Name $RunnerAccount -ErrorAction SilentlyContinue
if (-not $runner) {
    Write-Host "  ! $RunnerAccount does not exist - run runner-setup.ps1 first, then re-run this script" -ForegroundColor Yellow
} else {
    $sddl = "D:(A;;FA;;;BA)(A;;FA;;;SY)(A;;0x1200a9;;;$($runner.SID.Value))"

    $svc = New-Object -ComObject 'Schedule.Service'
    $svc.Connect()
    $folder = $svc.GetFolder('\')

    foreach ($t in $tasks.Keys) {
        $td = $svc.NewTask(0)
        $td.RegistrationInfo.Description = "IIS App Pool control for the mmfit.space deploy ($($tasks[$t]))"
        $td.Principal.UserId   = 'SYSTEM'
        $td.Principal.LogonType = 5   # TASK_LOGON_SERVICE_ACCOUNT
        $td.Principal.RunLevel  = 1   # TASK_RUNLEVEL_HIGHEST
        $td.Settings.Enabled = $true
        $td.Settings.StartWhenAvailable = $true
        $td.Settings.DisallowStartIfOnBatteries = $false
        $td.Settings.StopIfGoingOnBatteries = $false
        $td.Settings.ExecutionTimeLimit = 'PT5M'
        $td.Settings.MultipleInstances = 2   # IgnoreNew

        $action = $td.Actions.Create(0)      # TASK_ACTION_EXEC
        $action.Path = $appcmd
        $action.Arguments = $tasks[$t]

        # 6 = TASK_CREATE_OR_UPDATE, 5 = TASK_LOGON_SERVICE_ACCOUNT
        $folder.RegisterTaskDefinition($t, $td, 6, $null, $null, 5, $sddl) | Out-Null
        Write-Host "  + task $t (SYSTEM; $RunnerAccount may run it)" -ForegroundColor Green
    }
}

# ------------------------------------------------------------------ start
Start-WebAppPool -Name $AppPoolName -ErrorAction SilentlyContinue
if ((Get-Website -Name $SiteName).State -ne 'Started') { Start-Website -Name $SiteName }

Write-Host "`n=== Done ===" -ForegroundColor Cyan
Get-Website -Name $SiteName |
    Select-Object Name, State, PhysicalPath,
        @{n='Bindings'; e={ ($_.bindings.Collection | ForEach-Object { $_.protocol + '://' + $_.bindingInformation }) -join '  ' }} |
    Format-List
